output:
  - debug     # output all commands to stdout
  - serial    # send serial command e.g. to arduino
  - raspberry # direct control via GPIOS

input:
  - dualShock3
  #- dualShock4

plugins:
  - sixad
  - auto-pair
  - startup-sound
  #- dummy-data

devices:
  serial:
    - type: motor
      joystick: right
      pin: 6
      min: 0
      max: 180
      defaultPosition: 0
      reverse: true
      buffer: 10

    - type: ruder
      joystick: right
      pin: 9
      min: 0
      max: 200
      defaultPosition: 0
      reverse: true

    # water monitor
    - pin: 5
      type: setMovement
      min: 0
      max: 100
      joystick: left

    - pin: 13
      type: onOff
      button: circle

    - pin: 13
      type: autoOn
      button: circle

    - pin: 14
      type: onOff
      button: x

    - pin: 2
      type: press
      button: l2

    - pin: 3
      type: onOff
      button: l1

    - pin: 4
      type: timer
      button: r1
      time: 2000

    - pin: 10
      type: blink
      button: r2
      time_on: 1000
      time_off: 500

    - pin: 15
      min: 0
      max: 180
      type: increase
      button: square

    - type: speakText
      button: r2
      text: Test

    - type: soundFile
      button: r1
      file: horn.mp3

    - type: macro
      macro:
        - output d 1 1
        - sleep 1
        - controller 2
        - output d 1 0
      button: r1


  raspberry:
    # radar
    - pin: 4
      type: onOff
      button: triangle

    # licht
    - pin: 3
      type: onOff
      button: circle

    # leer
    # - pin: 2

    # blaulicht
    - pin: 17
      type: onOff
      button: x

  general:
    - type: restart
      button: psxButton


debug: true
motionDetection: false
soundExecutable: mplayer
speakExecutable: espeak

server:
  host: 0.0.0.0
  port: 3000
