input:
  dualShock3:
#    modes:
#      dpadRight:press: sound
#      dpadUp:press: licht

plugins:
  sixad:
  auto-pair:
  server:
    host: 0.0.0.0
    port: 3000
  startup-sound:
  #webcam:
  #controller-debug:
  #drive-control:
  #  relayPin:
  #    pin: 444
  #    device: arduino
  #  relayDelay: 2
  #  restartButton: start

devices:
  #  raspberry:
  #    type: raspberry # direct control via GPIOs
  #    actions:
  #      - pin: 2  # sonst Pin XXX
  #        name: Wasserpumpe
  #        type: press
  #        button: l2

  PCA-unten:
    type: i2c
    address: 0x40
    actions:
      - type: motor #links
        joystick: right
        pin: 1
        min: 1000
        max: 2200
        pwmType: ms

      - type: motor #rechts
        joystick: right
        pin: 0
        min: 1000
        max: 2200
        pwmType: ms

      - type: ruder
        joystick: right
        pin: 2
        min: 30
        max: 120

      - pin: 4
        name: Wasserpumpe
        type: press
        button: l2

      - type: setMovement
        name: Monitor-Rotation
        joystick: left
        pin: 5
        min: 0
        max: 180
        speed: 30

  PCA-oben:
    type: i2c
    address: 0x41
    actions:

      # Blaulicht
      - pin: 12
        name: Blaulicht
        button: x
        type: blink
        time_on: 350
        time_off: 700

      # Suchscheinwerfer
      - pin: 13
        name: Suchscheinwerfer
        type: onOff
        button: circle
        default: 1

      # Positionslichter
      - pin: 14
        name: Positionslichter
        type: onOff
        button: circle
        default: 1

      # Radar Motor
      - pin: 15
        name: Radar
        type: onOff
        button: triangle

  general:
    actions:
      - type: restart
        name: Neustart
        button: psxButton

      # disable events when "select" was pressed
      - type: mute
        name: Mute
        button: select

      # Sag "Es brennt"
      - type: speakText
        name: Sag "Hilfe! Es brennt"
        button: r2
        text: "Hilfe! Es brennt!"

      # play horn.mp3
      - type: soundFile
        name: Horn-Sound
        button: r1
        file: horn.mp3

      # set volume
      - type: setVolume
        name: Lautstärke setzen
        button+: r1  #lauter
        button-: l1  #leiser

soundExecutable: mpg123
speakExecutable: espeak -s80 -vde
debug: false
