output:
  - debug     # output all commands to stdout
  - serial    # send serial command e.g. to arduino
  - raspberry # direct control via GPIOS

input:
  - dualShock3

plugins:
  - sixad
  - startup-sound
  - auto-pair
 # - dummy-data

devices:
  serial:
    - type: motor
      joystick: right
      pin: 9
      min: 0
      max: 180
      buffer: 10
      defaultPosition: 0

    - type: ruder
      joystick: right
      pin: 6
      min: 20
      max: 200
      buffer: 0
      defaultPosition: 0

    # Water Monitor
    - pin: 5
      type: setMovement
      min: 0
      max: 180
      speed: 30
      joystick: left

    # Wasser Pumpe
    - pin: 2
      type: press
      button: l2

    # LED 13 (dummy)
    - pin: 13
      type: onOff
      button: circle

    # Dummy
    - pin: 14
      type: onOff
      button: x


  raspberry:
    # leer
    # - pin: 2

    # Radar Motor
    - pin: 4
      type: onOff
      button: triangle

    # Blaulicht
    - pin: 17
      button: x
      type: blink
      time_on: 350
      time_off: 700

    # Licht
    - pin: 3
      type: onOff
      button: circle

  general:
    - type: restart
      button: psxButton

    # Sound
    - type: speakText
      button: r2
      text: Test

    - type: soundFile
      button: r1
      file: horn.mp3

    # Dummy
    - type: macro
      macro:
        - output d 13 1
        - sleep 1
        - controller circle:press
        - output d 13 0
      button: r1

soundExecutable: mpg123
speakExecutable: espeak
debug: false
motionDetection: false

server:
  host: 0.0.0.0
  port: 80
