input:
  - dualShock3

plugins:
  - sixad
  - auto-pair
  - webcam
  - server:
    host: 0.0.0.0
    port: 3000
  - drive-control:
    relayPin:
      pin: 444
      device: arduino
    relayDelay: 2
    restartButton: start
  - startup-sound

output:
  arduino:
    type: serial # send serial command e.g. to arduino
  raspberry:
    type: raspberry # direct control via GPIOs
  esp1:
    type: firmata
    device: 192.168.100.100:3030

devices:
  arduino:
    - type: motor
      joystick: right
      pin: 9
      min: 0
      max: 180
      buffer: 10
      defaultPosition: 0
      relayPin: 999
      relayDelay: 3

    - type: ruder
      joystick: right
      pin: 6
      min: 20
      max: 200
      buffer: 0
      defaultPosition: 0

    # Water Monitor
    - pin: 5
      name: Monitor-Rotation
      type: setMovement
      min: 0
      max: 180
      defaultPosition: 90
      speed: 30
      joystick: left

    # Wasser Pumpe
    - pin: 2
      name: Wasserpumpe
      type: press
      button: l2

    # LED 13 (dummy)
    #- pin: 13
    #  type: onOff
    #  button: circle

    # Dummy
    #- pin: 14
    #  type: onOff
    #  button: x


  raspberry:
    # leer
    # - pin: 2

    # Radar Motor
    - pin: 4
      name: Radar
      type: onOff
      button: triangle

    # Blaulicht
    - pin: 17
      name: Blaulicht
      button: x
      type: blink
      time_on: 350
      time_off: 700

    # Licht
    - pin: 3
      name: Licht
      type: onOff
      button: circle
      default: 1

    # Dummy
    #- type: macro
    #  macro:
    #    - output d 13 1
    #    - sleep 1
    #    - input circle:press
    #    - output d 13 0
    #  button: r1

  esp1:
  - pin: 2
    name: Test
    button: x
    type: blink
    time_on: 350
    time_off: 700

  general:
    - type: restart
      name: Neustart
      button: psxButton

    # disable events when "select" was pressed
    - type: mute
      name: Mute
      button: select

    # Sag "Es brennt"
    - type: speakText
      name: Sag "Hilfe! Es brennt"
      button: r2
      text: "Hilfe! Es brennt!"

    # play horn.mp3
    - type: soundFile
      name: Horn-Sound
      button: r1
      file: horn.mp3

soundExecutable: mpg123
speakExecutable: espeak -s80 -vde
debug: false
motionDetection: false

