input:
  dualShock3:
    motionDetection: false

plugins:
  #sixad:
  #auto-pair:
  server:
    host: 0.0.0.0
    port: 3000
  startup-sound:
  #controller-debug:

devices:
  i2c:
    type: i2c
    actions:
      - type: ruder
        joystick: right
        pin: 1
        min: 50
        max: 120
        reversed: true

      - type: motor
        joystick: right
        pin: 2
        min: 50
        max: 120

      - pin: 3
        name: Test Servo 1
        type: setMovement
        min: 50
        max: 120
        speed: 30
        joystick: left

      - pin: 4
        name: Test Servo2
        type: setMovement
        min: 50
        max: 120
        speed: 30
        joystick: left

      # light
      - pin: 8
        name: LED
        button: x
        type: blink
        time_on: 350
        time_off: 700

      - pin: 8
        name: LED-2
        button: circle
        type: increaseWhenPressed
        time_on: 350
        time_off: 700

  general:
    actions:
      - type: restart
        name: Neustart
        button: psxButton

      # disable events when "select" was pressed
      - type: mute
        name: Mute
        button: select

      # Sag "Es brennt"
      - type: speakText
        name: Sag "Hilfe! Es brennt"
        button: r2
        text: "Hilfe! Es brennt!"

      # play horn.mp3
      - type: soundFile
        name: Horn-Sound
        button: r1
        file: horn.mp3

     # set volume
      - type: setVolume
        name: Lautstärke setzen
        button+: r1  #lauter
        button-: l1  #leiser

soundExecutable: mpg123
speakExecutable: espeak -s80 -vde
debug: true

