input:
#  dualShock3:
#    motionDetection: false
#    modes:
#      dpadRight:press: sound
#      dpadUp:press: licht

plugins:
  #sixad:
  auto-pair:
  #webcam:
  #controller-debug:
  server:
    host: 0.0.0.0
    port: 3000
  #drive-control:
  #  relayPin:
  #    pin: 444
  #    device: arduino
  #  relayDelay: 2
  #  restartButton: start
  startup-sound:

devices:
  raspberry:
    type: raspberry # direct control via GPIOs
    actions:
      - pin: 2  # sonst Pin XXX
        name: Wasserpumpe
        type: press
        button: l2

  PCA-unten:
    type: i2c
    # todo address
    actions:
      # PCA1 - Unten
      - type: ruder
        joystick: right
        pin: 0
        min: 30
        max: 120
        buffer: 0
        defaultPosition: 0

      - type: motor #links
        joystick: right
        pin: 1
        min: 1000
        max: 2000
        pwmType: ms
        #buffer: 10 ???
        reversed: false
        
      - type: motor #rechts
        joystick: right
        pin: 2
        min: 1000
        max: 2000
        pwmType: ms
        #buffer: 10 ???
        reversed: false

      - type: setMovement
        name: Monitor-Rotation # Water Monitor unten schwenken
        joystick: left
        pin: 5
        min: 0
        max: 180
        defaultPosition: 90
        speed: 30

       # todo über PCA9685 pin: 6 Monitor unten heben/senken (nicht vorhanden/Platzhalter)

  PCA-oben:
    type: i2c
    # todo address
    actions:
      # Radar Motor
      - pin: 1
        name: Radar
        type: onOff
        button: triangle

      # Blaulicht
      - pin: 2
        name: Blaulicht
        button: x
        type: blink
        time_on: 350
        time_off: 700

      # Licht
      - pin: 3
        name: Licht
        type: onOff
        button: circle
        default: 1

    # Water Monitor oben1 schwenken
 #   - pin: xxx
        # Water Monitor oben2 schwenken
 #   - pin: xxx
        # Water Monitor oben1 heben
 #   - pin: xxx
        # Water Monitor oben2 heben
  #   - pin: xxx

 # esp1:
 #   type: firmata
 #   address: 192.168.100.100:3030
 #   actions:
 #     - pin: 2
 #       name: Test
 #       button: x
 #       type: blink
 #       time_on: 350
 #       time_off: 700

  general:
    actions:
      - type: restart
        name: Neustart
        button: psxButton

      # disable events when "select" was pressed
      - type: mute
        name: Mute
        button: select

      # Sag "Es brennt"
      - type: speakText
        name: Sag "Hilfe! Es brennt"
        button: r2
        text: "Hilfe! Es brennt!"

      # play horn.mp3
      - type: soundFile
        name: Horn-Sound
        button: r1
        file: horn.mp3

      # set volume
      - type: setVolume
        name: Lautstärke setzen
        button+: r1  #lauter
        button-: l1  #leiser

soundExecutable: mpg123
speakExecutable: espeak -s80 -vde
debug: true
